/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HookFormRouteImport } from './routes/HookForm'
import { Route as ManualFormRouteImport } from './routes/ManualForm'
import { Route as ProfileRouteImport } from './routes/Profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HookFormRoute = HookFormRouteImport.update({
  id: '/HookForm',
  path: '/HookForm',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualFormRoute = ManualFormRouteImport.update({
  id: '/ManualForm',
  path: '/ManualForm',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/Profile',
  path: '/Profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/HookForm': typeof HookFormRoute
  '/ManualForm': typeof ManualFormRoute
  '/Profile': typeof ProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/HookForm': typeof HookFormRoute
  '/ManualForm': typeof ManualFormRoute
  '/Profile': typeof ProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/HookForm': typeof HookFormRoute
  '/ManualForm': typeof ManualFormRoute
  '/Profile': typeof ProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/HookForm' | '/ManualForm' | '/Profile'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/HookForm' | '/ManualForm' | '/Profile'
  id: '__root__' | '/' | '/HookForm' | '/ManualForm' | '/Profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HookFormRoute: typeof HookFormRoute
  ManualFormRoute: typeof ManualFormRoute
  ProfileRoute: typeof ProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/HookForm': {
      id: '/HookForm'
      path: '/HookForm'
      fullPath: '/HookForm'
      preLoaderRoute: typeof HookFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ManualForm': {
      id: '/ManualForm'
      path: '/ManualForm'
      fullPath: '/ManualForm'
      preLoaderRoute: typeof ManualFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Profile': {
      id: '/Profile'
      path: '/Profile'
      fullPath: '/Profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HookFormRoute: HookFormRoute,
  ManualFormRoute: ManualFormRoute,
  ProfileRoute: ProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
