import crypto from "node:crypto";

/**
 * Generate a PKCE code verifier.
 *
 * The verifier is a high-entropy random secret
 * generated by the OAuth client.
 */
export const generateCodeVerifier = () => {
    return crypto.randomBytes(32).toString("base64url");
}

/**
 * Generate a PKCE S256 code challenge from
 * the code verifier.
 *
 * code_challenge =
 * BASE64URL(
 *     SHA256(code_verifier)
 * )
 */
export const generateCodeChallenge = (codeVerifier) => {
    return crypto.createHash("sha256").update(codeVerifier).digest("base64url");
}

/**
 * Verify that a code verifier matches
 * the stored code challenge.
 */
export const verifyCodeChallenge = (codeVerifier, storedCodeChallenge) => {
    const calculatedCodeChallenge = generateCodeChallenge(codeVerifier);

    const calculatedBuffer = Buffer.from(calculatedCodeChallenge);
    const storedBuffer = Buffer.from(storedCodeChallenge);

    if(calculatedBuffer.length !== storedBuffer.length) {
        return false;
    }

    return crypto.timingSafeEqual(calculatedBuffer, storedBuffer);
}

/*

What does Buffer.from() do?

Node's crypto.timingSafeEqual() works with bytes, not normal JavaScript strings.

Your values are strings:

"E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM"

So:

Buffer.from(calculatedCodeChallenge)

converts the string into bytes.

Conceptually:

"E9Mel..."
       ↓
Buffer
       ↓
bytes

And:

Buffer.from(storedCodeChallenge)

does the same thing to the stored challenge.

So now:

crypto.timingSafeEqual(
    Buffer.from(calculatedCodeChallenge),
    Buffer.from(storedCodeChallenge)
)

is comparing the two byte sequences.

5. Why not just use ===?

You could technically write:

return calculatedCodeChallenge === storedCodeChallenge;

But cryptographic comparisons should generally use a constant-time comparison when appropriate.

Normal comparison:

a === b

can potentially finish as soon as it discovers a difference.

For example, conceptually:

ABCDEF
ABCXYZ
   ↑
difference found

A timing attack can potentially exploit tiny differences in how long comparisons take.

timingSafeEqual() is designed to avoid leaking information through comparison timing.

So for security-sensitive values:

crypto.timingSafeEqual(...)

is the safer pattern.

*/